package main

// ============================================================
// Lab 05 — Event Queues and Pub/Sub
// File: main.go  (Event Queue system)
// Role: Entry point — broker, producer, worker modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN:
//   Start broker:
//     ./queue_bin -mode broker -port 9000
//
//   Producer — enqueue a task:
//     ./queue_bin -mode produce -broker queue-broker:9000 -queue orders -payload "order-123"
//
//   Worker pool — process tasks:
//     ./queue_bin -mode work -broker queue-broker:9000 -queue orders -workers 3
//
//   Check queue depth:
//     ./queue_bin -mode status -broker queue-broker:9000 -queue orders
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"time"
)

func main() {
	mode    := flag.String("mode", "broker", "Mode: broker | produce | work | status")
	port    := flag.String("port", "9000", "Port for broker mode")
	broker  := flag.String("broker", "queue-broker:9000", "Broker address for client modes")
	queue   := flag.String("queue", "default", "Queue name")
	payload := flag.String("payload", "", "Task payload (produce mode)")
	workers := flag.Int("workers", 1, "Number of workers (work mode)")
	count   := flag.Int("count", 1, "Number of tasks to produce (produce mode)")
	flag.Parse()

	switch *mode {
	case "broker":
		runBroker(*port)
	case "produce":
		runProducer(*broker, *queue, *payload, *count)
	case "work":
		runWork(*broker, *queue, *workers)
	case "status":
		runStatus(*broker, *queue)
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode %q\n", *mode)
		os.Exit(1)
	}
}

func runBroker(port string) {
	fmt.Println("============================================")
	fmt.Println(" Lab 05 — Event Queue Broker")
	fmt.Printf(" Listening on port %s\n", port)
	fmt.Println("============================================")

	qm := NewQueueManager()
	if qm == nil {
		log.Fatal("[BROKER] NewQueueManager returned nil — complete Task 1")
	}

	if err := startRPCServer(qm, port); err != nil {
		log.Fatalf("[BROKER] Failed to start: %v", err)
	}

	qm.startStaleChecker()

	fmt.Println("[BROKER] Ready. Waiting for producers and workers...")
	select {}
}

func runProducer(brokerAddr, queueName, payload string, count int) {
	if payload == "" {
		payload = "task-payload"
	}
	for i := 0; i < count; i++ {
		p := payload
		if count > 1 {
			p = fmt.Sprintf("%s-%d", payload, i)
		}
		var reply EnqueueReply
		err := callRPC(brokerAddr, "QueueRPC.Enqueue",
			&EnqueueArgs{QueueName: queueName, Payload: p}, &reply)
		if err != nil {
			log.Fatalf("[PRODUCER] Enqueue failed: %v", err)
		}
		fmt.Printf("✅ [PRODUCER] Enqueued task=%s payload=%q to queue=%q\n",
			reply.TaskID, p, queueName)
		time.Sleep(50 * time.Millisecond)
	}
}

func runWork(brokerAddr, queueName string, numWorkers int) {
	fmt.Printf("[WORK] Starting %d workers on queue %q\n", numWorkers, queueName)
	RunWorkerPool(brokerAddr, queueName, numWorkers)

	// Keep running so workers keep processing
	select {}
}

func runStatus(brokerAddr, queueName string) {
	// Status uses a direct RPC since it is read-only debugging
	var reply EnqueueReply // reuse simple struct just to check connectivity
	err := callRPC(brokerAddr, "QueueRPC.Enqueue",
		&EnqueueArgs{QueueName: "__healthcheck__", Payload: "ping"}, &reply)
	if err != nil {
		fmt.Printf("❌ Cannot reach broker: %v\n", err)
		return
	}
	fmt.Printf("✅ Broker is reachable at %s\n", brokerAddr)
	fmt.Println("   (Check broker terminal logs for queue depth details)")
}
