package main

// ============================================================
// Lab 03 — CAP Theorem
// File: main.go  (CP System)
// Role: Entry point — server and CLI modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN (inside your container):
//
//   Start CP node server:
//     ./cp_bin -mode server -port 8000 -peers cp-node2:8000,cp-node3:8000,cp-node4:8000,cp-node5:8000
//
//   Use CLI:
//     ./cp_bin -mode cli -port 8000 put mykey myvalue
//     ./cp_bin -mode cli -port 8000 get mykey
//     ./cp_bin -mode cli -port 8000 ping
//
//   Recompile after editing:
//     go build -o cp_bin .
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

func main() {
	mode  := flag.String("mode", "server", "Run mode: 'server' or 'cli'")
	port  := flag.String("port", "8000", "Port this node listens on")
	peers := flag.String("peers", "", "Comma-separated peer addresses e.g. cp-node2:8000,cp-node3:8000")
	flag.Parse()

	switch *mode {
	case "server":
		runServer(*port, *peers)
	case "cli":
		runCLI(*port, flag.Args())
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode %q — use 'server' or 'cli'\n", *mode)
		os.Exit(1)
	}
}

func runServer(port, peersStr string) {
	var peerList []string
	if peersStr != "" {
		peerList = strings.Split(peersStr, ",")
	}

	addr := fmt.Sprintf("0.0.0.0:%s", port)
	n := NewNode(addr, peerList)
	if n == nil {
		log.Fatal("[CP] NewNode returned nil — did you implement Task 9?")
	}

	fmt.Println("============================================")
	fmt.Printf(" Lab 03 — CP Node\n")
	fmt.Printf(" Listening : :%s\n", port)
	fmt.Printf(" Peers     : %d\n", len(peerList))
	fmt.Printf(" Quorum    : %d/%d\n", n.quorum, len(peerList)+1)
	fmt.Println("============================================")

	if err := startRPCServer(n, port); err != nil {
		log.Fatalf("[CP] Failed to start RPC server: %v", err)
	}

	time.Sleep(500 * time.Millisecond)
	log.Printf("[CP] Node ready. Use: ./cp_bin -mode cli -port %s <command>", port)

	select {}
}

func runCLI(port string, args []string) {
	nodeAddr := fmt.Sprintf("127.0.0.1:%s", port)

	if len(args) == 0 {
		printCPUsage()
		return
	}

	switch args[0] {
	case "put":
		if len(args) < 3 {
			fmt.Println("Usage: cp_bin -mode cli -port <port> put <key> <value>")
			return
		}
		var reply PutReply
		err := callRPC(nodeAddr, "CPRPC.Put", &PutArgs{Key: args[1], Value: args[2]}, &reply)
		if err != nil {
			log.Fatalf("put failed: %v", err)
		}
		if reply.Err != "" {
			fmt.Printf("❌ Put failed: %s\n", reply.Err)
		} else {
			fmt.Printf("✅ Stored  key=%q  value=%q\n", args[1], args[2])
		}

	case "get":
		if len(args) < 2 {
			fmt.Println("Usage: cp_bin -mode cli -port <port> get <key>")
			return
		}
		var reply GetReply
		err := callRPC(nodeAddr, "CPRPC.Get", &GetArgs{Key: args[1]}, &reply)
		if err != nil {
			log.Fatalf("get failed: %v", err)
		}
		if reply.Err != "" {
			fmt.Printf("❌ Get failed: %s\n", reply.Err)
		} else if reply.Found {
			fmt.Printf("✅ key=%q  value=%q\n", args[1], reply.Value)
		} else {
			fmt.Printf("❌ key=%q not found\n", args[1])
		}

	case "ping":
		err := callRPC(nodeAddr, "CPRPC.Ping", &PingArgs{}, &PingReply{})
		if err != nil {
			fmt.Printf("❌ Node not responding: %v\n", err)
		} else {
			fmt.Println("✅ CP node is alive")
		}

	default:
		fmt.Printf("Unknown command: %q\n", args[0])
		printCPUsage()
	}
}

func printCPUsage() {
	fmt.Println(`
CP Node CLI — Usage:
  ./cp_bin -mode cli -port <port> <command>

Commands:
  put <key> <value>   Store a key-value pair (requires quorum)
  get <key>           Retrieve a value (requires quorum — always consistent)
  ping                Check if node is running
`)
}
