package main

// ============================================================
// Lab 04 — RPC and Web Services
// File: store.go
// Role: Shared thread-safe key-value store
//       Used by ALL THREE implementations (net/rpc, gRPC, REST)
//
// DO NOT EDIT THIS FILE
// ============================================================

import (
	"fmt"
	"sync"
)

// Store is a thread-safe in-memory key-value store.
// All three server implementations (net/rpc, gRPC, REST) share
// one instance of this store — so data is consistent regardless
// of which protocol you use to access it.
type Store struct {
	mu   sync.RWMutex
	data map[string]string
}

// NewStore creates and returns an empty store
func NewStore() *Store {
	return &Store{data: make(map[string]string)}
}

// Put stores a key-value pair
func (s *Store) Put(key, value string) {
	s.mu.Lock()
	defer s.mu.Unlock()
	s.data[key] = value
	fmt.Printf("[STORE] Put  key=%-20q  value=%q\n", key, value)
}

// Get retrieves a value by key
func (s *Store) Get(key string) (string, bool) {
	s.mu.RLock()
	defer s.mu.RUnlock()
	v, ok := s.data[key]
	return v, ok
}

// Delete removes a key from the store
func (s *Store) Delete(key string) bool {
	s.mu.Lock()
	defer s.mu.Unlock()
	_, ok := s.data[key]
	if ok {
		delete(s.data, key)
		fmt.Printf("[STORE] Del  key=%q\n", key)
	}
	return ok
}

// List returns all keys in the store
func (s *Store) List() []string {
	s.mu.RLock()
	defer s.mu.RUnlock()
	keys := make([]string, 0, len(s.data))
	for k := range s.data {
		keys = append(keys, k)
	}
	return keys
}

// Size returns the number of keys
func (s *Store) Size() int {
	s.mu.RLock()
	defer s.mu.RUnlock()
	return len(s.data)
}
