package main

// ============================================================
// Lab 03 — CAP Theorem
// File: main.go  (AP System)
// Role: Entry point — server and CLI modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN (inside your container):
//
//   Start AP node server:
//     ./ap_bin -mode server -port 7000 -peers ap-node2:7000,ap-node3:7000,ap-node4:7000,ap-node5:7000
//
//   Use CLI:
//     ./ap_bin -mode cli -port 7000 put mykey myvalue
//     ./ap_bin -mode cli -port 7000 get mykey
//     ./ap_bin -mode cli -port 7000 store
//     ./ap_bin -mode cli -port 7000 ping
//
//   Recompile after editing:
//     go build -o ap_bin .
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
	"strings"
	"time"
)

func main() {
	mode  := flag.String("mode", "server", "Run mode: 'server' or 'cli'")
	port  := flag.String("port", "7000", "Port this node listens on")
	peers := flag.String("peers", "", "Comma-separated peer addresses e.g. ap-node2:7000,ap-node3:7000")
	flag.Parse()

	switch *mode {
	case "server":
		runServer(*port, *peers)
	case "cli":
		runCLI(*port, flag.Args())
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode %q — use 'server' or 'cli'\n", *mode)
		os.Exit(1)
	}
}

func runServer(port, peersStr string) {
	var peerList []string
	if peersStr != "" {
		peerList = strings.Split(peersStr, ",")
	}

	addr := fmt.Sprintf("0.0.0.0:%s", port)
	n := NewNode(addr, peerList)
	if n == nil {
		log.Fatal("[AP] NewNode returned nil — did you implement Task 1?")
	}

	fmt.Println("============================================")
	fmt.Printf(" Lab 03 — AP Node\n")
	fmt.Printf(" Listening : :%s\n", port)
	fmt.Printf(" Peers     : %d\n", len(peerList))
	fmt.Println("============================================")

	if err := startRPCServer(n, port); err != nil {
		log.Fatalf("[AP] Failed to start RPC server: %v", err)
	}

	n.startSync()

	time.Sleep(500 * time.Millisecond)
	log.Printf("[AP] Node ready. Use: ./ap_bin -mode cli -port %s <command>", port)

	select {}
}

func runCLI(port string, args []string) {
	nodeAddr := fmt.Sprintf("127.0.0.1:%s", port)

	if len(args) == 0 {
		printAPUsage()
		return
	}

	switch args[0] {
	case "put":
		if len(args) < 3 {
			fmt.Println("Usage: ap_bin -mode cli -port <port> put <key> <value>")
			return
		}
		var reply PutReply
		err := callRPC(nodeAddr, "APRPC.Put", &PutArgs{Key: args[1], Value: args[2]}, &reply)
		if err != nil {
			log.Fatalf("put failed: %v", err)
		}
		fmt.Printf("✅ Stored  key=%q  value=%q\n", args[1], args[2])

	case "get":
		if len(args) < 2 {
			fmt.Println("Usage: ap_bin -mode cli -port <port> get <key>")
			return
		}
		var reply GetReply
		err := callRPC(nodeAddr, "APRPC.Get", &GetArgs{Key: args[1]}, &reply)
		if err != nil {
			log.Fatalf("get failed: %v", err)
		}
		if reply.Found {
			fmt.Printf("✅ key=%q  value=%q\n", args[1], reply.Value)
		} else {
			fmt.Printf("❌ key=%q not found\n", args[1])
		}

	case "ping":
		err := callRPC(nodeAddr, "APRPC.Ping", &PingArgs{}, &PingReply{})
		if err != nil {
			fmt.Printf("❌ Node not responding: %v\n", err)
		} else {
			fmt.Println("✅ AP node is alive")
		}

	case "store":
		fmt.Println("Store contents are shown in the server terminal logs.")

	default:
		fmt.Printf("Unknown command: %q\n", args[0])
		printAPUsage()
	}
}

func printAPUsage() {
	fmt.Println(`
AP Node CLI — Usage:
  ./ap_bin -mode cli -port <port> <command>

Commands:
  put <key> <value>   Store a key-value pair
  get <key>           Retrieve a value (returns local value — may be stale)
  ping                Check if node is running
  store               Show local store contents
`)
}
