package main

// ============================================================
// Lab 04 — RPC and Web Services
// File: grpc_client.go  (gRPC client)
// Role: Connect to gRPC server and call methods
//
// TASK IN THIS FILE:
//   Task 7 — Implement GRPCClient
// ============================================================

// ── HOW gRPC CLIENT WORKS ─────────────────────────────────
//
// gRPC client workflow:
//   1. grpc.Dial(addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
//      → open connection
//   2. pb.NewKeyValueStoreClient(conn)
//      → create typed client stub (auto-generated by protoc)
//   3. client.Put(ctx, &pb.PutRequest{Key: key, Value: value})
//      → call method — looks just like a local function call!
//   4. conn.Close()
//      → disconnect
//
// Compare with net/rpc:
//   net/rpc:  client.Call("KVHandler.Put", args, &reply)  (string method name)
//   gRPC:     client.Put(ctx, &pb.PutRequest{...})        (type-safe, generated)
//
// ──────────────────────────────────────────────────────────

import (
	"context"
	"fmt"
	"time"

	pb "lab04client/proto"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"
)

// GRPCClient wraps a gRPC connection and the generated client stub
type GRPCClient struct {
	addr   string
	conn   *grpc.ClientConn
	client pb.KeyValueStoreClient
}

// ============================================================
// TASK 7 — Implement GRPCClient
// ============================================================
//
// ── Connect ───────────────────────────────────────────────
// Steps:
//   1. Dial: grpc.Dial(g.addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
//      Store result in g.conn
//   2. Create client stub: g.client = pb.NewKeyValueStoreClient(g.conn)
//   3. Print: [gRPC] Connected to addr
//
// TODO: implement
func (g *GRPCClient) Connect() error {
	// YOUR CODE HERE
	conn, err := grpc.Dial(g.addr, grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		return err
	}
	g.conn = conn
	g.client = pb.NewKeyValueStoreClient(conn)
	fmt.Printf("[gRPC] Connected to %s\n", g.addr)
	return nil
}

// ── Put ───────────────────────────────────────────────────
// Create a context with 5 second timeout
// Call g.client.Put(ctx, &pb.PutRequest{Key: key, Value: value})
// Return error if call fails
//
// HINT: ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
//       defer cancel()
//
// TODO: implement
func (g *GRPCClient) Put(key, value string) error {
	// YOUR CODE HERE
	if g.client == nil {
		return fmt.Errorf("not connected")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	_, err := g.client.Put(ctx, &pb.PutRequest{Key: key, Value: value})
	return err
}

// ── Get ───────────────────────────────────────────────────
// Call g.client.Get(ctx, &pb.GetRequest{Key: key})
// Return resp.Value, resp.Found, error
//
// TODO: implement
func (g *GRPCClient) Get(key string) (string, bool, error) {
	// YOUR CODE HERE
	if g.client == nil {
		return "", false, fmt.Errorf("not connected")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	resp, err := g.client.Get(ctx, &pb.GetRequest{Key: key})
	if err != nil {
		return "", false, err
	}
	return resp.Value, resp.Found, nil
}

// ── Delete ────────────────────────────────────────────────
// Call g.client.Delete(ctx, &pb.DeleteRequest{Key: key})
// Return resp.Deleted, error
//
// TODO: implement
func (g *GRPCClient) Delete(key string) (bool, error) {
	// YOUR CODE HERE
	if g.client == nil {
		return false, fmt.Errorf("not connected")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	resp, err := g.client.Delete(ctx, &pb.DeleteRequest{Key: key})
	if err != nil {
		return false, err
	}
	return resp.Deleted, nil
}

// ── List ──────────────────────────────────────────────────
// Call g.client.List(ctx, &pb.ListRequest{})
// Return resp.Keys, error
//
// TODO: implement
func (g *GRPCClient) List() ([]string, error) {
	// YOUR CODE HERE
	if g.client == nil {
		return nil, fmt.Errorf("not connected")
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	resp, err := g.client.List(ctx, &pb.ListRequest{})
	if err != nil {
		return nil, err
	}
	return resp.Keys, nil
}

// ── Close ─────────────────────────────────────────────────
// Close the connection: g.conn.Close()
//
// TODO: implement
func (g *GRPCClient) Close() {
	// YOUR CODE HERE
	if g.conn != nil {
		g.conn.Close()
	}
}

// NewGRPCClient creates a new GRPCClient for the given address
func NewGRPCClient(addr string) *GRPCClient {
	return &GRPCClient{addr: addr}
}
