package main

// ============================================================
// Lab 04 — RPC and Web Services
// File: main.go  (client)
// Role: CLI + benchmark runner
//
// DO NOT EDIT THIS FILE
//
// HOW TO USE:
//   # Individual commands
//   ./client_bin rpc put city London
//   ./client_bin grpc get city
//   ./client_bin rest delete city
//   ./client_bin rest list
//
//   # Benchmark — compare all three
//   ./client_bin bench 100
//
//   # All protocols at once
//   ./client_bin all put city London
//   ./client_bin all get city
// ============================================================

import (
	"fmt"
	"os"
	"strconv"
	"strings"
	"time"
)

const (
	SERVER_HOST = "lab04-server"
	RPC_ADDR    = SERVER_HOST + ":7000"
	GRPC_ADDR   = SERVER_HOST + ":7001"
	REST_URL    = "http://" + SERVER_HOST + ":8080"
)

func main() {
	if len(os.Args) < 2 {
		printUsage()
		return
	}

	protocol := os.Args[1]
	if protocol == "bench" {
		n := 100
		if len(os.Args) >= 3 {
			n, _ = strconv.Atoi(os.Args[2])
		}
		runBenchmark(n)
		return
	}

	if len(os.Args) < 3 {
		printUsage()
		return
	}

	cmd := os.Args[2]
	if len(os.Args) < 4 && protocol != "all" && cmd != "list" {
		printUsage()
		return
	}
	key := ""
	value := ""
	if len(os.Args) >= 4 { key = os.Args[3] }
	if len(os.Args) >= 5 { value = os.Args[4] }

	switch protocol {
	case "rpc":
		runRPC(cmd, key, value)
	case "grpc":
		runGRPC(cmd, key, value)
	case "rest":
		runREST(cmd, key, value)
	case "all":
		if len(os.Args) >= 4 { cmd = os.Args[2]; key = os.Args[3] }
		if len(os.Args) >= 5 { value = os.Args[4] }
		fmt.Println("── net/rpc ──────────────────")
		runRPC(cmd, key, value)
		fmt.Println("── gRPC ─────────────────────")
		runGRPC(cmd, key, value)
		fmt.Println("── REST ─────────────────────")
		runREST(cmd, key, value)
	default:
		printUsage()
	}
}

func runRPC(cmd, key, value string) {
	c := NewRPCClient(RPC_ADDR)
	if err := c.Connect(); err != nil {
		fmt.Printf("❌ net/rpc connect failed: %v\n", err)
		return
	}
	defer c.Close()
	execCmd("net/rpc", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func runGRPC(cmd, key, value string) {
	c := NewGRPCClient(GRPC_ADDR)
	if err := c.Connect(); err != nil {
		fmt.Printf("❌ gRPC connect failed: %v\n", err)
		return
	}
	defer c.Close()
	execCmd("gRPC", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func runREST(cmd, key, value string) {
	c := NewRESTClient(REST_URL)
	execCmd("REST", cmd, key, value,
		func() error { return c.Put(key, value) },
		func() (string, bool, error) { return c.Get(key) },
		func() (bool, error) { return c.Delete(key) },
		func() ([]string, error) { return c.List() },
	)
}

func execCmd(proto, cmd, key, value string,
	putFn func() error,
	getFn func() (string, bool, error),
	delFn func() (bool, error),
	listFn func() ([]string, error)) {

	switch cmd {
	case "put":
		if err := putFn(); err != nil {
			fmt.Printf("❌ [%s] put failed: %v\n", proto, err)
		} else {
			fmt.Printf("✅ [%s] Stored key=%q value=%q\n", proto, key, value)
		}
	case "get":
		val, found, err := getFn()
		if err != nil {
			fmt.Printf("❌ [%s] get failed: %v\n", proto, err)
		} else if found {
			fmt.Printf("✅ [%s] key=%q value=%q\n", proto, key, val)
		} else {
			fmt.Printf("❌ [%s] key=%q not found\n", proto, key)
		}
	case "delete":
		deleted, err := delFn()
		if err != nil {
			fmt.Printf("❌ [%s] delete failed: %v\n", proto, err)
		} else if deleted {
			fmt.Printf("✅ [%s] Deleted key=%q\n", proto, key)
		} else {
			fmt.Printf("❌ [%s] key=%q not found\n", proto, key)
		}
	case "list":
		keys, err := listFn()
		if err != nil {
			fmt.Printf("❌ [%s] list failed: %v\n", proto, err)
		} else {
			fmt.Printf("✅ [%s] %d keys: %v\n", proto, len(keys), keys)
		}
	default:
		fmt.Printf("Unknown command: %s\n", cmd)
	}
}

func runBenchmark(n int) {
	fmt.Printf("\n══════════════════════════════════════════════\n")
	fmt.Printf(" Lab 04 — Benchmark: %d operations per protocol\n", n)
	fmt.Printf("══════════════════════════════════════════════\n\n")

	results := map[string]time.Duration{}

	// net/rpc benchmark
	rpcC := NewRPCClient(RPC_ADDR)
	if err := rpcC.Connect(); err != nil {
		fmt.Printf("❌ net/rpc not available: %v\n", err)
	} else {
		start := time.Now()
		for i := 0; i < n; i++ {
			key := fmt.Sprintf("bench-key-%d", i)
			rpcC.Put(key, "value")
			rpcC.Get(key)
		}
		results["net/rpc"] = time.Since(start)
		rpcC.Close()
	}

	// gRPC benchmark
	grpcC := NewGRPCClient(GRPC_ADDR)
	if err := grpcC.Connect(); err != nil {
		fmt.Printf("❌ gRPC not available: %v\n", err)
	} else {
		start := time.Now()
		for i := 0; i < n; i++ {
			key := fmt.Sprintf("bench-key-%d", i)
			grpcC.Put(key, "value")
			grpcC.Get(key)
		}
		results["gRPC"] = time.Since(start)
		grpcC.Close()
	}

	// REST benchmark
	restC := NewRESTClient(REST_URL)
	start := time.Now()
	success := 0
	for i := 0; i < n; i++ {
		key := fmt.Sprintf("bench-key-%d", i)
		if err := restC.Put(key, "value"); err == nil {
			if _, _, err2 := restC.Get(key); err2 == nil {
				success++
			}
		}
	}
	if success > 0 {
		results["REST"] = time.Since(start)
	} else {
		fmt.Println("❌ REST not available")
	}

	// Print results
	fmt.Printf("\n── Results (%d put+get pairs) ─────────────────\n", n)
	fmt.Printf("  %-12s  %-12s  %-12s  %s\n", "Protocol", "Total time", "Avg/op", "Ops/sec")
	fmt.Println("  " + strings.Repeat("─", 52))
	for _, proto := range []string{"net/rpc", "gRPC", "REST"} {
		if d, ok := results[proto]; ok {
			ops := float64(n * 2) // put + get
			avg := d / time.Duration(n*2)
			opsPerSec := ops / d.Seconds()
			fmt.Printf("  %-12s  %-12s  %-12s  %.0f\n",
				proto, d.Round(time.Millisecond),
				avg.Round(time.Microsecond), opsPerSec)
		}
	}
	fmt.Println()
	fmt.Println("── Observations ─────────────────────────────")
	fmt.Println("  Which protocol was fastest? Why?")
	fmt.Println("  Can you call the REST server with curl? (Try it!)")
	fmt.Println("  Can you call net/rpc with curl? Why not?")
	fmt.Println()
}

func printUsage() {
	fmt.Println(`
Lab 04 Client — Usage:
  ./client_bin <protocol> <command> [key] [value]

Protocols:  rpc | grpc | rest | all
Commands:   put <key> <value> | get <key> | delete <key> | list

Examples:
  ./client_bin rpc  put city London
  ./client_bin grpc get city
  ./client_bin rest delete city
  ./client_bin rest list
  ./client_bin all  put city London    # same operation, all 3 protocols
  ./client_bin bench 100               # benchmark all 3 with 100 ops
`)
}
