package main

// ============================================================
// Lab 05 — Event Queues and Pub/Sub
// File: main.go  (Pub/Sub system)
// Role: Entry point — broker, publish, subscribe modes
//
// DO NOT EDIT THIS FILE
//
// HOW TO RUN:
//   Start broker:
//     ./pubsub_bin -mode broker -port 9001
//
//   Publisher — publish an event:
//     ./pubsub_bin -mode publish -broker pubsub-broker:9001 -topic orders -key order1 -value created
//
//   Subscriber — listen for events on a topic:
//     ./pubsub_bin -mode subscribe -broker pubsub-broker:9001 -topic orders -id sub1 -port 9100
// ============================================================

import (
	"flag"
	"fmt"
	"log"
	"os"
)

func main() {
	mode    := flag.String("mode", "broker", "Mode: broker | publish | subscribe")
	port    := flag.String("port", "9001", "Port (broker mode = broker port, subscribe mode = subscriber's own port)")
	broker  := flag.String("broker", "pubsub-broker:9001", "Broker address for client modes")
	topic   := flag.String("topic", "default", "Topic name")
	key     := flag.String("key", "", "Event key (publish mode)")
	value   := flag.String("value", "", "Event value (publish mode)")
	count   := flag.Int("count", 1, "Number of events to publish")
	subID   := flag.String("id", "sub1", "Subscriber ID (subscribe mode)")
	myHost  := flag.String("host", "", "This subscriber's own hostname (for broker callback)")
	flag.Parse()

	switch *mode {
	case "broker":
		runBroker(*port)
	case "publish":
		runPublish(*broker, *topic, *key, *value, *count)
	case "subscribe":
		runSubscribe(*broker, *topic, *subID, *port, *myHost)
	default:
		fmt.Fprintf(os.Stderr, "Unknown mode %q\n", *mode)
		os.Exit(1)
	}
}

func runBroker(port string) {
	fmt.Println("============================================")
	fmt.Println(" Lab 05 — Pub/Sub Broker")
	fmt.Printf(" Listening on port %s\n", port)
	fmt.Println("============================================")

	b := NewBroker()
	if b == nil {
		log.Fatal("[BROKER] NewBroker returned nil — complete Task 8")
	}

	if err := startBrokerRPCServer(b, port); err != nil {
		log.Fatalf("[BROKER] Failed to start: %v", err)
	}

	fmt.Println("[BROKER] Ready. Waiting for publishers and subscribers...")
	select {}
}

func runPublish(brokerAddr, topic, key, value string, count int) {
	if value == "" {
		value = "event-data"
	}
	for i := 0; i < count; i++ {
		k := key
		v := value
		if count > 1 {
			k = fmt.Sprintf("%s-%d", key, i)
			v = fmt.Sprintf("%s-%d", value, i)
		}
		var reply PublishReply
		err := callRPC(brokerAddr, "BrokerRPC.Publish",
			&PublishArgs{Topic: topic, Key: k, Value: v}, &reply)
		if err != nil {
			log.Fatalf("[PUBLISH] Failed: %v", err)
		}
		fmt.Printf("✅ [PUBLISH] topic=%q key=%q value=%q → delivered to %d subscribers\n",
			topic, k, v, reply.DeliveredTo)
	}
}

func runSubscribe(brokerAddr, topic, subID, myPort, myHost string) {
	fmt.Println("============================================")
	fmt.Println(" Lab 05 — Pub/Sub Subscriber")
	fmt.Printf(" ID: %s   Topic: %s\n", subID, topic)
	fmt.Println("============================================")

	if myHost == "" {
		myHost = "localhost"
	}
	myAddr := fmt.Sprintf("%s:%s", myHost, myPort)

	subRPC := NewSubscriberRPC()
	if err := startSubscriberRPCServer(subRPC, myPort); err != nil {
		log.Fatalf("[SUBSCRIBE] Failed to start own RPC server: %v", err)
	}

	var reply SubscribeReply
	err := callRPC(brokerAddr, "BrokerRPC.Subscribe",
		&SubscribeArgs{Topic: topic, SubID: subID, SubAddr: myAddr}, &reply)
	if err != nil {
		log.Fatalf("[SUBSCRIBE] Failed to subscribe: %v", err)
	}
	fmt.Printf("[SUBSCRIBE] Subscribed to topic=%q — waiting for events...\n", topic)

	subRPC.PrintEvents() // blocks forever, printing each received event
}
